sudo: required

services:
  - docker

before_install:
   # install heroku CLI
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  # login to docker registries (dockerhub + heroku)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com

language: node_js
node_js:
  - "10"
cache:
  directories:
  - node_modules

script:
  - npm test

  # master
  - test $TRAVIS_BRANCH = "master" && docker build -f Dockerfile -t $DOCKER_USERNAME/7552-web-app .
  - test $TRAVIS_BRANCH = "master" && docker tag $DOCKER_USERNAME/7552-web-app registry.heroku.com/$HEROKU_APP_NAME/web
  # develop
  - test $TRAVIS_BRANCH = "develop" && docker build -f Dockerfile -t $DOCKER_USERNAME/7552-web-app:develop .
  - test $TRAVIS_BRANCH = "develop" && docker tag $DOCKER_USERNAME/7552-web-app:develop registry.heroku.com/$HEROKU_APP_NAME_DEVELOP/web

deploy:
  - provider: script
    script:
      # push to dockerhub
      docker push josemorelli/7552-web-app
      docker push registry.heroku.com/$HEROKU_APP_NAME/web
      heroku container:release web --app $HEROKU_APP_NAME
    on:
      branch: master
  - provider: script
    script:
      # push to dockerhub
      docker push josemorelli/7552-web-app:develop
      docker push registry.heroku.com/$HEROKU_APP_NAME_DEVELOP/web
      heroku container:release web --app $HEROKU_APP_NAME_DEVELOP
    on:
      branch: develop